name: Trigger Terraform Workflow
on:
  push:
    branches:
      - master

jobs:
  trigger_another_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Terraform Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: Food-Fusion-Fiap/terraform-lambda
          event-type: trigger-terraform